### ISSUE TITLE
Court circuit avec 

### ISSUE THREAD

**Issue by cyrilcalvez** [sylvainlebras/EMC-Tools#1]
Bonjour Sylvain,
Sur le layout du DM/CM separator, il y a un court circuit entre le pin 2 du switch S2, qui se connecte à R2 et le GND.
![image](https://user-images.githubusercontent.com/16023641/125209864-3eb8b500-e29c-11eb-8a18-7b178a14e840.png)
En supprimant la connexion au GND tout fonctionne correctement avec le LISN et le transient limiter.
Les résultats obtenus sur mon setup de test sont comparables avec un LISN R&S HM6050-2, la séparation des modes communs/différentiels ainsi que l'utilisation possible d'une alimentation DC en plus!
Merci pour avoir mis à disposition toutes ces cartes, permettant de se faire un labo CEM performant et peu onéreux!

**Comment by sylvainlebras** [comment]
Bonjour,
C'est corrigé, et la version du séparateur est passée à C.
Merci beaucoup pour votre retour sur le problème rencontré et sur la fonctionnalité du kit.
Cordialement
